import * as yup from 'yup';
export const schemaData = {
    'Analyzer' : {
        Name: yup.string().required('required'),
        Vendor: yup.string().required('required'),
        Desc: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'AnalyzerParameter' : {
        AnalyzerId: yup.number().required('required'),
        LISCodeId: yup.number().required('required'),
        LASCodeId: yup.number().required('required'),
        // isActive: yup.boolean().required('required'),
        Desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Cpt' : {
        name: yup.string().required('required'),
        description: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'LisCode' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestParameter' : {
        cptid: yup.number().required('required'),
        liscodeId: yup.number().required('required'),
        unit: yup.string().required('required'),
        range: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'GenLookup' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    // ==================
    'InvoiceDetail' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'InvoiceMaster' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'OrderDetail' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'OrderMaster' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyPendingQueue' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyResultDetail' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyResultMaster' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'RoleModule' : {
        roleId: yup.string().required('required'),
        moduleId: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Module' : {
        roleId: yup.string().required('required'),
        moduleId: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Role' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestCategorie' : {
        categoryName: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestSample' : {
        cptid: yup.string().required('required'),
        sampleName: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestUnit' : {
        name: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'User' : {
        name: yup.string().required('required'),
        mobile: yup.string().required('required'),
        email: yup.string().required('required'),
        username: yup.string().required('required'),
        password: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'His' : {
        name: yup.string().required('required'),
        // type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'HISAnalyzer' : {
        'Analyzer' : {
            AnalyzerID: yup.number().required('required'),
            AnalyzerCode: yup.string().required('required'),
            AParamName: yup.string().required('required'),
            AUnit: yup.string().required('required'),
            ARange: yup.string().required('required'),

        },
        'HIS' : {
            HISID: yup.number().required('required'),
            HISCode: yup.string().required('required'),
            HParamName: yup.string().required('required'),
            HUnit: yup.string().required('required'),
            HRange: yup.string().required('required'),

        }
    },
}